# Generated by Django 3.0.8 on 2020-08-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
